"""create tables

Revision ID: 045c9d5052f4
Revises: 
Create Date: 2020-11-04 05:04:25.720677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045c9d5052f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playerOneId', sa.Integer(), nullable=False),
    sa.Column('playerTwoId', sa.Integer(), nullable=False),
    sa.Column('playerQuit', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('board', sa.String(length=40), nullable=False),
    sa.Column('winner', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['playerOneId'], ['players.id'], ),
    sa.ForeignKeyConstraint(['playerTwoId'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playerId', sa.Integer(), nullable=False),
    sa.Column('gameId', sa.Integer(), nullable=False),
    sa.Column('column', sa.Integer()),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('movedOn', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gameId'], ['games.id'], ),
    sa.ForeignKeyConstraint(['playerId'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moves')
    op.drop_table('games')
    op.drop_table('players')
    # ### end Alembic commands ###
